CREATE TABLE IF NOT EXISTS Molecules (
    MOLECULE_ID SERIAL,
    NAME TEXT UNIQUE NOT NULL,
    PRIMARY KEY (MOLECULE_ID)
);

CREATE TABLE IF NOT EXISTS Atoms (
    ATOM_ID SERIAL,
    ELEMENT_CODE VARCHAR(3) NOT NULL,
    X DECIMAL(7, 4) NOT NULL,
    Y DECIMAL(7, 4) NOT NULL,
    Z DECIMAL(7, 4) NOT NULL,
    PRIMARY KEY (ATOM_ID)
);

CREATE TABLE IF NOT EXISTS Bonds (
    BOND_ID SERIAL,
    A1 INTEGER NOT NULL,
    A2 INTEGER NOT NULL,
    EPAIRS INTEGER NOT NULL,
    PRIMARY KEY (BOND_ID),
    FOREIGN KEY (A1) REFERENCES Atoms(ATOM_ID) DEFERRABLE INITIALLY DEFERRED, 
    FOREIGN KEY (A2) REFERENCES Atoms(ATOM_ID) DEFERRABLE INITIALLY DEFERRED 
);

	
CREATE TABLE IF NOT EXISTS MoleculeAtom (
    MOLECULE_ID INTEGER NOT NULL,
    ATOM_ID INTEGER NOT NULL,
    PRIMARY KEY (MOLECULE_ID, ATOM_ID),
    FOREIGN KEY (MOLECULE_ID) REFERENCES Molecules(MOLECULE_ID) DEFERRABLE INITIALLY DEFERRED ,
    FOREIGN KEY (ATOM_ID) REFERENCES Atoms(ATOM_ID) DEFERRABLE INITIALLY DEFERRED 
);

CREATE TABLE IF NOT EXISTS MoleculeBond (
    MOLECULE_ID INTEGER NOT NULL,
    BOND_ID INTEGER NOT NULL,
    PRIMARY KEY (MOLECULE_ID, BOND_ID),
    FOREIGN KEY (MOLECULE_ID) REFERENCES Molecules(MOLECULE_ID) DEFERRABLE INITIALLY DEFERRED ,
    FOREIGN KEY (BOND_ID) REFERENCES Bonds(BOND_ID) DEFERRABLE INITIALLY DEFERRED 
);

CREATE TABLE IF NOT EXISTS Elements (
    ELEMENT_NO INTEGER NOT NULL,
    ELEMENT_CODE VARCHAR(3) NOT NULL, 
    ELEMENT_NAME VARCHAR(32) NOT NULL, 
    COLOUR1 CHAR(6) NOT NULL, 
    COLOUR2 CHAR(6) NOT NULL, 
    COLOUR3 CHAR(6) NOT NULL, 
    Radius DECIMAL(3) NOT NULL, 
    PRIMARY KEY (ELEMENT_CODE)
);